include: [path: ../compose.yaml]
services:
  sonarr:
    labels:
      traefik.enable: 'true'
      traefik.http.routers.sonarr.middlewares: compress-response@file
      traefik.http.routers.sonarr.tls: 'true'
      traefik.http.services.sonarr.loadbalancer.server.port: '8989'
    extends: { file: ../service-templates.yaml, service: custom-io }
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - { type: volume, source: sonarr_config, target: /config }
    secrets:
      - { source: sonarr_database-password, target: database-password }
      - { source: sonarr_api-key, target: api-key }
    environment:
      SONARR__APP__LAUNCHBROWSER: 'False'
      FILE__SONARR__AUTH__APIKEY: /run/secrets/api-key
      SONARR__AUTH__METHOD: Forms
      SONARR__AUTH__REQUIRED: Enabled
      SONARR__LOG__LEVEL: info
      SONARR__LOG__ANALYTICSENABLED: 'False'
      SONARR__LOG__DBENABLED: 'False'
      SONARR__POSTGRES__HOST: postgres
      SONARR__POSTGRES__USER: sonarr
      FILE__SONARR__POSTGRES__PASSWORD: /run/secrets/database-password
      SONARR__POSTGRES__MAINDB: sonarr
    hostname: sonarr
    healthcheck: { test: 'curl --silent --show-error --fail http://localhost:8989/ping || exit 1' }
volumes:
  sonarr_config: { }
secrets:
  sonarr_database-password: { file: ../.secrets/sonarr_database-password }
  sonarr_api-key: { file: ../.secrets/sonarr_api-key }
